[build]
  base = "client"
  command = "npm run build -- --configuration production"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "18"

# API proxy Eurostat 
[[redirects]]
  from = "/api/*"
  to = "https://ec.europa.eu/eurostat/api/dissemination/:splat"
  status = 200
  force = true

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200